from data_structure import dataFrame
import tracker_utils
from calc import goals, shots,distance_covered,passes_completed,passes_attempted,sprints,recoveries,interceptions,minutes_played,max_speed,challenges_won,challenges_lost,aerial_duals_lost,aerial_duals_won,fouls_recieved,completed_crosses,tackles_won,tackles_lost
